# Generated by Django 3.2.9 on 2021-11-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('subject', models.CharField(choices=[('computing-science', 'วิทยาการคำนวณ'), ('design-and-technology', 'การออกแบบและเทคโนโลยี')], max_length=100)),
                ('score', models.IntegerField()),
                ('Grade', models.CharField(choices=[('4', '4'), ('3.5', '3.5'), ('3', '3'), ('2.5', '2.5'), ('2', '2'), ('1.5', '1.5'), ('1', '1'), ('0', '0')], max_length=50)),
            ],
        ),
    ]
