# Generated by Django 3.2.9 on 2021-11-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='subject',
            field=models.CharField(choices=[('วิทยาการคำนวณ', 'วิทยาการคำนวณ'), ('คอมพิวเตอร์พื้นฐาน', 'คอมพิวเตอร์พื้นฐาน')], max_length=100),
        ),
    ]
