# Generated by Django 3.2.9 on 2022-02-22 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='name_comment',
            new_name='name',
        ),
    ]
